# Generated by Django 5.1.7 on 2025-03-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='guests',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
